apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evanshortiss-poi-backend-app-dev
  annotations:
    argocd/app-name: evanshortiss-poi-backend-app-dev
    backstage.io/kubernetes-id: evanshortiss-poi-backend-app
    backstage.io/kubernetes-namespace: evanshortiss
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-vegas/evanshortiss-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/dev-pipelines/ns/evanshortiss/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/k8s/ns/evanshortiss/deployments/evanshortiss-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/#https://github.com/rhdh-vegas/evanshortiss-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/evanshortiss"
  system: workshop-system-evanshortiss
  providesApis:
    - backend-api-evanshortiss
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-evanshortiss
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/evanshortiss"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-evanshortiss
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://evanshortiss-poi-backend-app-evanshortiss.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-vegas/evanshortiss-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/evanshortiss"
  system: workshop-system-evanshortiss
  definition:
    $text: https://github.com/rhdh-vegas/evanshortiss-backend/tree/main/src/main/resources/META-INF/openapi.yaml
